services:
  scheduler:
    build: .
    command: dask scheduler

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DASK_IP=scheduler
    depends_on:
      - scheduler

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: dask worker scheduler:8786
